# Generated by Django 2.0.4 on 2018-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Article_Short_Descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Article_title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
