# Generated by Django 2.0.4 on 2018-06-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_auto_20180618_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='search_fields',
        ),
    ]
