# Generated by Django 2.0.4 on 2018-06-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_remove_post_search_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image',
        ),
    ]
